### ISSUE TITLE
数据集评估：大模型生成的问题不存在于数据集中

### ISSUE THREAD

**Issue by LeopoldSimmons** [ruili33/SEC#1]
感谢您们团队优秀的工作！我在阅读论文的过程中产生了一个问题，论文中描述到在SEC中是让大模型自己生成问题并回答问题，但是大模型生成的问题很有可能并没有存在数据集中，这个如何在数据集上面进行评估的呢？

**Comment by ruili33** [comment]
We have already replied your concern by email!
